### ISSUE TITLE
Unable to find specification for TwilioVoice 2.0.0-beta15

### ISSUE THREAD

**Issue by ppierson** [twilio/cocoapod-specs#104]
I'm getting an error when trying to include the cocoapod `pod 'TwilioVoice', '2.0.0-beta15'`:
```
[!] Unable to find a specification for `TwilioVoice (= 2.0.0-beta15)`
```

I am including the following sources in my pod file:
```
source 'https://github.com/twilio/cocoapod-specs'
source 'https://github.com/CocoaPods/Specs'
```

**Comment by rbeiter** [comment]
Hi @ppierson,

Your pod and source lines look good above.  Did you run `pod repo update` to ensure you have the latest specs locally before running `pod install`?

Thank you,
Randy

**Comment by ppierson** [comment]
That worked, thank you for the quick reply!
