### ISSUE TITLE
pod install is failing in a fresh install of cocoapods

### ISSUE THREAD

**Issue by m-revetria** [twilio/cocoapod-specs#19]
Hi,

In a new Mac where I just installed cocoapods, I'm not being able to run `pod install` successfully. I'm getting this error:

```shell
Cloning spec repo `twilio` from `https://github.com/twilio/cocoapod-specs`
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `TwilioCommon (= 0.2.2)` required by `Podfile.lock`
- `TwilioCommon (>= 0.2.2, ~> 0.3.0)` required by `TwilioIPMessagingClient (0.14.2)`

Specs satisfying the `TwilioCommon (= 0.2.2), TwilioCommon (>= 0.2.2, ~> 0.3.0)` dependency were found, but they required a higher minimum deployment target.
```

I'm using cocoapods version 1.0.1. My Podfile looks pretty similar to this:

```ruby
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'
platform :ios, '8.1'
use_frameworks!

# Add Application pods here
abstract_target 'App' do
    # Other additional pods
    pod 'TwilioIPMessagingClient'

    target 'Target Production' do
    end

    target 'Target Staging' do
    end
end
```

Previously to commit  [bf2cc7d](https://github.com/twilio/cocoapod-specs/commit/bf2cc7dcc0746968be442da5a66cbd351135fab4#diff-a4e0dd1573e4fe8722764b49b8cac1d7) it was running fine.

**Comment by rbeiter** [comment]
Hi Miguel,

Our apologies - if you perform a `git repo update` now then a `pod install` this should be resolved with the latest commit.

Please let us know if you run into any other issues.

Thank you,
Randy

**Comment by m-revetria** [comment]
Hi Randy,

Latest version is installing correctly after running `git repo update`

Thanks for your help!
Miguel
