### ISSUE TITLE
TVIRoomDelegate method has wrong nonnull keyword

### ISSUE THREAD

**Issue by allu22** [twilio/cocoapod-specs#37]
TVIRoomDelegate in TVIRoom.h has method:
```objc
- (void)room:(nonnull TVIRoom *)room didFailToConnectWithError:(nonnull NSError *)error;
```

This error can be `null`. I am able to reproduce it when I initialise TVIVideoClient with malformed token.

**Comment by paynerc** [comment]
Thanks for reporting this. We are indeed aware of the issue and it will be fixed in the next Beta release.

**Comment by ceaglest** [comment]
@allu22 As of `1.0.0-beta2` you should always receive an NSError when you fail to connect to a Room. We are still improving error handling in our Video SDK, but the API contract in TVIRoomDelegate should be satisfied.
