### ISSUE TITLE
1.0.0-preview1, 1.0.0-beta4 what does they mean?

### ISSUE THREAD

**Issue by betzerra** [twilio/cocoapod-specs#48]
![screenshot 2016-12-15 16 14 22](https://cloud.githubusercontent.com/assets/681600/21274240/eaeab19a-c3a5-11e6-88d7-a6dedad1f058.png)

Which one is supposed to be more stable?

**Comment by ptankTwilio** [comment]
Latest Video SDK version 1.0.0-beta4 is more stable.

**Comment by girtis** [comment]
Resolved, closing
