### ISSUE TITLE
The calls are not dial via DATA connections. It is DIAL via voice roaming

### ISSUE THREAD

**Issue by hieplebstar** [twilio/cocoapod-specs#54]
Hi,
I'm using the TwillioVoiceClient (2.0.0-beta5) SDK + CallKit framework to develop iOS voice app. But I got a problem: I used the app when traveling (not wifi). I used the APP to make calls and now I got the telecom bill. The calls are not dial via DATA connections. It is DIAL via voice roaming (I have 3G data in overseas, but not voice). Skype does not have voice roaming fee but the app now has. The telecom bill is per voice min (not per KB)
Do you have any idea. Because now in this case, I have to pay for both Twillio and Telecom provider for each calling minute. Please help!

**Comment by bchen-twilio** [comment]
Hi @hieplebstar,

Sorry that you are experiencing such problem. This is a known issue of the SDK and we are actively fixing it. Once we have a solution, would you help us give it a try?
We apologize again and please bear with us at the moment.

-bobie

**Comment by hieplebstar** [comment]
Thanks Bobie

**Comment by bchen-twilio** [comment]
Hi @hieplebstar 

Just got a latest release-candidate which has the solution to prefer wifi over cellular. Do you mind giving it one more chance? here's the link to the patch https://drive.google.com/file/d/0B0jCXbOI9plrcXV0SzQ4dWtKTDA/view?usp=sharing

I've tried a few configurations even with wifi on but cellular off for the app itself (cellular is on systemwide) and checked the Xcode debugger, the Network page showed `en0` when connection over wifi is expected.

Let us know how it goes.
Thanks
-bobie

**Comment by hieplebstar** [comment]
Sorry for reply later, I will try now. and get back to you soon. Thanks so much

**Comment by bchen-twilio** [comment]
Hi @hieplebstar 
Thanks for getting back. The good new is we've just released Voice 2.0.0-beta6 last week. Please run `pod repo update` and update the Podfile to give the latest beta6 a try.
Thanks a lot!
-bobie

**Comment by hieplebstar** [comment]
Ok Bobie

**Comment by bchen-twilio** [comment]
Hi @hieplebstar 

How are things?
I am assuming the latest beta6 has also resolved this issue for you.
I am closing this ticket and please feel free to create issues if you run into any in the future:
Obj-C:
github.com/twilio/voice-quickstart-objc
Swift:
github.com/twilio/voice-quickstart-swift

Cheers,
-bobie

**Comment by hieplebstar** [comment]
Thanks Bobie
