### ISSUE TITLE
TwilioChatClient.framework/TwilioChatClient is 55.46 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

### ISSUE THREAD

**Issue by zallanx** [twilio/cocoapod-specs#71]
I get this warning when pushing to Github about the size of the client. Anything to reduce size would be much appreciated.

**Comment by bchen-twilio** [comment]
Hi Allen,

The best practice would be to keep updating the reference to the Twilio SDK, namely the `Podfile`, in your application repository, and do `pod install/update` locally. Is there any reason that you want to include the framework into the repository?

-bobie
Twilio SDK Engineering.

**Comment by zallanx** [comment]
Thanks for pointing that out Bobie. I included the entire app directory, which produced this error. As you've recommended, it's better to do this locally.
