### ISSUE TITLE
It is slience and not sound

### ISSUE THREAD

**Issue by hieplebstar** [twilio/cocoapod-specs#73]
Hi, the problem is I am calling another phone number,  after I type in the numbers 12345678, I put my ear to the phone. It is slience and not sound. Normal call, my ear should hear dial tone (tuk...tuk... ) and now it is ringing , and I am waiting for the other party to pick up

**Comment by bchen-twilio** [comment]
Hi @hieplebstar 

Could you create an issue in the corresponding project quickstart? I am guessing you are experiencing trouble using the Voice iOS SDK?

**Comment by idelgado** [comment]
https://github.com/twilio/voice-quickstart-objc
https://github.com/twilio/voice-quickstart-swift

**Comment by hieplebstar** [comment]
Thanks!!
