### ISSUE TITLE
Compilation warning for TwilioVoice/2.0.0-beta8 iOS SDK

### ISSUE THREAD

**Issue by diejmon** [twilio/cocoapod-specs#75]
```
<module-includes>:1:1: warning: umbrella header for module 'TwilioVoice' does not include header 'TwilioVoiceClient.h'
#import "Headers/TwilioVoice.h"
```

I manually added framework to Xcode project.

**Comment by bchen-twilio** [comment]
Hi @diejmon 

Sorry for the breaking changes we introduced, but we have modified the face object and the framework name to `TwilioVoice`.
Here's the [changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog).

`TwilioVoiceClient` is history now.

-bobie

**Comment by diejmon** [comment]
Xcode got mad. Closing.
