### ISSUE TITLE
Is TwilioConversationsClient deprecated? 

### ISSUE THREAD

**Issue by vysotsky** [twilio/cocoapod-specs#80]
Hi guys! I cannot find any useful information whether or not the conversations client has been deprecated.
Should I start using the new Video framework? Or TwilioConversationsClient is still relevant?

**Comment by paynerc** [comment]
Hey Vysotsky,

Thanks for reaching out! Conversations has been deprecated for quite some time now, with the last Conversations iOS release in [July 2016](https://www.twilio.com/docs/api/video/conversations-api-deprecated/changelogs/ios). The deprecation notice is available here: https://www.twilio.com/docs/api/video/conversations-api-deprecated.

[Twilio Video](https://www.twilio.com/docs/api/video) has been released as GA on [April 26, 2017](https://www.twilio.com/docs/api/video/changelogs/ios). Twilio Video for iOS is also available from the [CocoaPods](https://cocoapods.org/pods/TwilioVideo).

Thanks!

Ryan
